# Generated by Django 6.0.4 on 2026-04-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Cabernet', 'Cabernet'), ('Chardonnay', 'Chardonnay'), ('Malbec', 'Malbec'), ('Merlot', 'Merlot')], max_length=50)),
            ],
        ),
    ]
